<script>
  import ConfigPanel from "./components/ConfigPanel.svelte";
  import Briefing from "./components/Briefing.svelte";
  import RawJson from "./components/RawJson.svelte";
  import Settings from "./components/Settings.svelte";
  import { defaultConfig, deriveFacts, buildPrompt } from "./lib/scenario.js";
  import { briefer, browserSupported } from "./lib/llm.js";

  let config = $state(defaultConfig());

  // Recomputes live as the config changes — this is the JS-derived input.
  const derived = $derived(deriveFacts(config));

  let status = $state("idle"); // idle | loading | streaming | error
  let progress = $state(0);
  let statusText = $state(""); // human-readable phase from the engine
  let text = $state("");
  let reasoning = $state(""); // a reasoning model's thinking, if any
  let stats = $state(null); // { outputTokens, tokPerSec, finishReason }
  let error = $state("");
  let controller = null; // AbortController for the in-flight generation

  const supported = browserSupported();

  async function generate() {
    if (!supported) {
      status = "error";
      error = "WebGPU isn't available in this browser. Try Chrome or Edge (or Safari 18+).";
      return;
    }
    text = "";
    reasoning = "";
    stats = null;
    error = "";
    progress = 0;
    statusText = "Preparing model…";
    status = "loading";
    controller = new AbortController();
    let genStart = 0;
    let genTokens = 0; // self-counted: the WebLLM provider reports usage: 0
    let finishReason = "stop";
    try {
      const prompt = buildPrompt(config);
      let first = true;
      const opts = {
        signal: controller.signal,
        onProgress: (r) => {
          progress = r.progress;
          if (r.text) statusText = r.text;
        },
        onFinish: ({ finishReason: fr }) => {
          if (fr) finishReason = fr;
        },
        params: {
          temperature: config.temperature,
          topP: config.topP,
          maxOutputTokens: config.maxOutputTokens,
          frequencyPenalty: config.frequencyPenalty,
        },
      };
      for await (const part of briefer.stream(config.model, prompt, opts)) {
        if (first) {
          status = "streaming";
          statusText = "Generating…";
          genStart = performance.now();
          first = false;
        }
        genTokens += 1; // WebLLM streams roughly one token per part
        if (part.kind === "reasoning") reasoning += part.text;
        else text += part.text;
      }
      const secs = genStart ? (performance.now() - genStart) / 1000 : 0;
      stats = {
        outputTokens: genTokens,
        tokPerSec: secs > 0 ? Math.round(genTokens / secs) : 0,
        finishReason,
      };
      status = "idle";
    } catch (e) {
      // A user-triggered abort isn't an error — keep whatever streamed.
      if (e?.name === "AbortError" || controller?.signal.aborted) {
        status = "idle";
        statusText = "Stopped.";
      } else {
        status = "error";
        error = e?.message ?? String(e);
      }
    } finally {
      controller = null;
    }
  }

  function stop() {
    controller?.abort();
  }

  const busy = $derived(status === "loading" || status === "streaming");
</script>

<main>
  <header>
    <h1>Work-Order Briefing</h1>
    <p class="tagline">
      Structured metadata → a spoken dispatch, generated by a small model running entirely in your
      browser. No server, no API keys.
    </p>
    {#if !supported}
      <p class="warn">⚠ WebGPU not detected — generation will fail. Use Chrome, Edge, or Safari 18+.</p>
    {/if}
  </header>

  <div class="grid">
    <ConfigPanel bind:config disabled={busy} />
    <div class="right-col">
      <Briefing
        {text}
        {reasoning}
        {stats}
        {status}
        {progress}
        {statusText}
        {error}
        onGenerate={generate}
        onStop={stop}
      />
      <Settings bind:config disabled={busy} />
    </div>
  </div>

  <RawJson facts={derived.facts} />

  <footer>
    <span>Model runs locally via WebGPU · <code>{config.model}</code></span>
  </footer>
</main>
